# Generated by Django 5.1.6 on 2025-02-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='SchoolSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Literature', 'Literature'), ('History', 'History'), ('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Philosophy', 'Philosophy'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.student')),
            ],
        ),
    ]
