# Generated by Django 5.1.6 on 2025-02-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_schoolsubjects_schoolsubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Literature', 'Literature'), ('History', 'History'), ('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Philosophy', 'Philosophy'), ('Computer Science', 'Computer Science'), ('Geography', 'Geography')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Literature', 'Literature'), ('History', 'History'), ('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Philosophy', 'Philosophy'), ('Computer Science', 'Computer Science'), ('Geography', 'Geography')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Literature', 'Literature'), ('History', 'History'), ('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Philosophy', 'Philosophy'), ('Computer Science', 'Computer Science'), ('Geography', 'Geography')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.teacher'),
        ),
    ]
