# Generated by Django 5.1.6 on 2025-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_photo_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='media/teachers/url-foto', null=True, upload_to='teachers/'),
        ),
    ]
