# Generated by Django 5.1.6 on 2025-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='students/default.jpg', null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='teachers/default.jpg', null=True, upload_to='teachers/'),
        ),
    ]
